### ISSUE TITLE
Write up things we wrote on the board

### ISSUE THREAD

**Issue by jiahao** [jiahao/paper-benchmark#1]
Board 1

![2016-04-08 18 42 29](https://cloud.githubusercontent.com/assets/1732/14908322/c6733746-0da3-11e6-84df-82b92856637e.jpg)

I don't have a picture of Board 2

**Comment by jrevels** [comment]
![img_20160420_184015919](https://cloud.githubusercontent.com/assets/3277443/14926782/e5d2a7a2-0e1b-11e6-8da5-54eae970ccd4.jpg)

**Comment by jrevels** [comment]
Close the first photo but with some other stuff on the left side:

![img_20160408_153305058](https://cloud.githubusercontent.com/assets/3277443/14926819/2958fa8a-0e1c-11e6-873a-2f89be5cdd67.jpg)

**Comment by jiahao** [comment]
Closed by fc1303d
